.PHONY: dev install lint test bench bench-update openapi-generate openapi-check

dev:
	doppler run -- uvicorn app.main:app --reload --port 8000

install:
	uv venv && uv pip install -e ".[dev]"

lint:
	ruff check . && mypy .

test:
	doppler run -- pytest

bench:
	python3 scripts/run_benchmark.py --iterations 30 --warmup 3

bench-update:
	python3 scripts/run_benchmark.py --iterations 30 --warmup 3 --update-baseline

# Regenerate Pydantic v2 models from the contracts OpenAPI spec.
# Equivalent to `openapi:generate` in the Node SDK pilot (octomil-node#94).
# Requires octomil-contracts to be checked out alongside this repo at ../octomil-contracts.
openapi-generate:
	OCTOMIL_PYTHON_PATH=$$PWD OCTOMIL_PYTHON=1 OCTOMIL_SKIP_INSTALL=1 \
	  ../octomil-contracts/tools/sdkgen/generate-python.sh
	uv run ruff format octomil/_generated/types.py

# Verify the generated file exists and has the correct AUTOGENERATED banner.
# Fails non-zero with a fix-command hint if out of date.
openapi-check:
	python3 scripts/check_openapi_banner.py
