#!/usr/bin/env python3
"""Verify that octomil/_generated/types.py exists and has the correct AUTOGENERATED banner.

This is the Python equivalent of scripts/check_openapi_banner.mjs in octomil-node (PR #94).
Exits non-zero with a fix-command hint if the file is missing or the banner is stale.

Usage:
    python3 scripts/check_openapi_banner.py
"""

from __future__ import annotations

import sys
from pathlib import Path

GENERATED_FILE = Path(__file__).parent.parent / "octomil" / "_generated" / "types.py"
EXPECTED_GENERATOR = "datamodel-code-generator==0.27.0"
BANNER_MARKER = "AUTOGENERATED"
GENERATOR_MARKER = f"# Generator:  {EXPECTED_GENERATOR}"
FIX_HINT = (
    "Run `make openapi-generate` (or "
    "OCTOMIL_PYTHON_PATH=$PWD OCTOMIL_PYTHON=1 OCTOMIL_SKIP_INSTALL=1 "
    "../octomil-contracts/tools/sdkgen/generate-python.sh) "
    "and commit the result."
)


def main() -> int:
    if not GENERATED_FILE.exists():
        print(f"ERROR: {GENERATED_FILE} does not exist.", file=sys.stderr)
        print(f"Fix:   {FIX_HINT}", file=sys.stderr)
        return 1

    content = GENERATED_FILE.read_text(encoding="utf-8")
    lines = content.splitlines()

    if not lines:
        print(f"ERROR: {GENERATED_FILE} is empty.", file=sys.stderr)
        print(f"Fix:   {FIX_HINT}", file=sys.stderr)
        return 1

    # Check AUTOGENERATED banner on the first line.
    if BANNER_MARKER not in lines[0]:
        print(
            f"ERROR: {GENERATED_FILE} is missing the AUTOGENERATED banner on line 1.",
            file=sys.stderr,
        )
        print(f"       Found: {lines[0]!r}", file=sys.stderr)
        print(f"Fix:   {FIX_HINT}", file=sys.stderr)
        return 1

    # Check generator pin in the first 10 lines (banner block).
    header = "\n".join(lines[:10])
    if GENERATOR_MARKER not in header:
        print(
            f"ERROR: {GENERATED_FILE} banner does not report {EXPECTED_GENERATOR}.",
            file=sys.stderr,
        )
        print(
            "       The file may have been generated with a different version pin.",
            file=sys.stderr,
        )
        print(f"Fix:   {FIX_HINT}", file=sys.stderr)
        return 1

    print(f"OK: {GENERATED_FILE} has a valid AUTOGENERATED banner ({EXPECTED_GENERATOR}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
